package github.nbanexus.model;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Data
@AllArgsConstructor
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class PlayerBase {
  private List<PlayerSearch> playerBase;

  public PlayerBase() {
    this.playerBase = new ArrayList<>();
    initializeList();
  }
  
  private void initializeList() {
  playerBase.add(new PlayerSearch(4870562, "Dominick Barlow", "Dominick Barlow"));
  playerBase.add(new PlayerSearch(3037789, "Bogdan Bogdanovic", "Bogdan Bogdanovic"));
  playerBase.add(new PlayerSearch(4683736, "Kobe Bufkin", "Kobe Bufkin"));
  playerBase.add(new PlayerSearch(3102529, "Clint Capela", "Clint Capela"));
  playerBase.add(new PlayerSearch(4869342, "Dyson Daniels", "Dyson Daniels"));
  playerBase.add(new PlayerSearch(4712863, "Mouhamed Gueye", "Mouhamed Gueye"));
  playerBase.add(new PlayerSearch(4067858, "Kevon Harris", "Kevon Harris"));
  playerBase.add(new PlayerSearch(4065732, "De'Andre Hunter", "De'Andre Hunter"));
  playerBase.add(new PlayerSearch(4701230, "Jalen Johnson", "Jalen Johnson"));
  playerBase.add(new PlayerSearch(4578893, "Vit Krejci", "Vit Krejci"));
  playerBase.add(new PlayerSearch(4431775, "Seth Lundy", "Seth Lundy"));
  playerBase.add(new PlayerSearch(3913180, "Garrison Mathews", "Garrison Mathews"));
  playerBase.add(new PlayerSearch(2580365, "Larry Nance Jr.", "Larry Nance Jr."));
  playerBase.add(new PlayerSearch(4431680, "Onyeka Okongwu", "Onyeka Okongwu"));
  playerBase.add(new PlayerSearch(5211175, "Zaccharie Risacher", "Zaccharie Risacher"));
  playerBase.add(new PlayerSearch(4593041, "David Roddy", "David Roddy"));
  playerBase.add(new PlayerSearch(4279118, "Keaton Wallace", "Keaton Wallace"));
  playerBase.add(new PlayerSearch(4277905, "Trae Young", "Trae Young"));
  playerBase.add(new PlayerSearch(2579258, "Cody Zeller", "Cody Zeller"));
  playerBase.add(new PlayerSearch(3917376, "Jaylen Brown", "Jaylen Brown"));
  playerBase.add(new PlayerSearch(4576085, "JD Davison", "JD Davison"));
  playerBase.add(new PlayerSearch(4431734, "Tristan Enaruna", "Tristan Enaruna"));
  playerBase.add(new PlayerSearch(4397251, "Ron Harper Jr.", "Ron Harper Jr."));
  playerBase.add(new PlayerSearch(4065804, "Sam Hauser", "Sam Hauser"));
  playerBase.add(new PlayerSearch(3995, "Jrue Holiday", "Jrue Holiday"));
  playerBase.add(new PlayerSearch(3213, "Al Horford", "Al Horford"));
  playerBase.add(new PlayerSearch(3064560, "Luke Kornet", "Luke Kornet"));
  playerBase.add(new PlayerSearch(4397689, "Drew Peterson", "Drew Peterson"));
  playerBase.add(new PlayerSearch(3102531, "Kristaps Porzingis", "Kristaps Porzingis"));
  playerBase.add(new PlayerSearch(4066354, "Payton Pritchard", "Payton Pritchard"));
  playerBase.add(new PlayerSearch(4397424, "Neemias Queta", "Neemias Queta"));
  playerBase.add(new PlayerSearch(4593841, "Baylor Scheierman", "Baylor Scheierman"));
  playerBase.add(new PlayerSearch(4432164, "Jaden Springer", "Jaden Springer"));
  playerBase.add(new PlayerSearch(4065648, "Jayson Tatum", "Jayson Tatum"));
  playerBase.add(new PlayerSearch(4277964, "Xavier Tillman", "Xavier Tillman"));
  playerBase.add(new PlayerSearch(4277890, "Lonnie Walker IV", "Lonnie Walker IV"));
  playerBase.add(new PlayerSearch(4683689, "Jordan Walsh", "Jordan Walsh"));
  playerBase.add(new PlayerSearch(4431705, "Anton Watson", "Anton Watson"));
  playerBase.add(new PlayerSearch(3078576, "Derrick White", "Derrick White"));
  playerBase.add(new PlayerSearch(4277869, "Jose Alvarado", "Jose Alvarado"));
  playerBase.add(new PlayerSearch(4278572, "Jamal Cain", "Jamal Cain"));
  playerBase.add(new PlayerSearch(2596112, "Javonte Green", "Javonte Green"));
  playerBase.add(new PlayerSearch(4683750, "Jordan Hawkins", "Jordan Hawkins"));
  playerBase.add(new PlayerSearch(3056245, "Malcolm Hill", "Malcolm Hill"));
  playerBase.add(new PlayerSearch(3913176, "Brandon Ingram", "Brandon Ingram"));
  playerBase.add(new PlayerSearch(4395623, "Trey Jemison", "Trey Jemison"));
  playerBase.add(new PlayerSearch(4277813, "Herbert Jones", "Herbert Jones"));
  playerBase.add(new PlayerSearch(4997538, "Karlo Matkovic", "Karlo Matkovic"));
  playerBase.add(new PlayerSearch(2490149, "CJ McCollum", "CJ McCollum"));
  playerBase.add(new PlayerSearch(5061589, "Yves Missi", "Yves Missi"));
  playerBase.add(new PlayerSearch(4397688, "Trey Murphy III", "Trey Murphy III"));
  playerBase.add(new PlayerSearch(3907497, "Dejounte Murray", "Dejounte Murray"));
  playerBase.add(new PlayerSearch(4592686, "Antonio Reeves", "Antonio Reeves"));
  playerBase.add(new PlayerSearch(4432813, "Jeremiah Robinson-Earl", "Jeremiah Robinson-Earl"));
  playerBase.add(new PlayerSearch(3908336, "Matt Ryan", "Matt Ryan"));
  playerBase.add(new PlayerSearch(2451037, "Daniel Theis", "Daniel Theis"));
  playerBase.add(new PlayerSearch(4395628, "Zion Williamson", "Zion Williamson"));
  playerBase.add(new PlayerSearch(4066421, "Lonzo Ball", "Lonzo Ball"));
  playerBase.add(new PlayerSearch(4438552, "Onuralp Bitim", "Onuralp Bitim"));
  playerBase.add(new PlayerSearch(4711294, "Matas Buzelis", "Matas Buzelis"));
  playerBase.add(new PlayerSearch(3133635, "Jevon Carter", "Jevon Carter"));
  playerBase.add(new PlayerSearch(2528693, "Torrey Craig", "Torrey Craig"));
  playerBase.add(new PlayerSearch(4431943, "Marcus Domask", "Marcus Domask"));
  playerBase.add(new PlayerSearch(4397002, "Ayo Dosunmu", "Ayo Dosunmu"));
  playerBase.add(new PlayerSearch(4592402, "Chris Duarte", "Chris Duarte"));
  playerBase.add(new PlayerSearch(4871145, "Josh Giddey", "Josh Giddey"));
  playerBase.add(new PlayerSearch(4396991, "Talen Horton-Tucker", "Talen Horton-Tucker"));
  playerBase.add(new PlayerSearch(3064440, "Zach LaVine", "Zach LaVine"));
  playerBase.add(new PlayerSearch(4432821, "E.J. Liddell", "E.J. Liddell"));
  playerBase.add(new PlayerSearch(4585610, "Kenneth Lofton Jr.", "Kenneth Lofton Jr."));
  playerBase.add(new PlayerSearch(5105553, "Julian Phillips", "Julian Phillips"));
  playerBase.add(new PlayerSearch(4702023, "Adama Sanogo", "Adama Sanogo"));
  playerBase.add(new PlayerSearch(4397189, "Jalen Smith", "Jalen Smith"));
  playerBase.add(new PlayerSearch(4701231, "DJ Steward", "DJ Steward"));
  playerBase.add(new PlayerSearch(4433159, "Dalen Terry", "Dalen Terry"));
  playerBase.add(new PlayerSearch(6478, "Nikola Vucevic", "Nikola Vucevic"));
  playerBase.add(new PlayerSearch(4395651, "Coby White", "Coby White"));
  playerBase.add(new PlayerSearch(4431687, "Patrick Williams", "Patrick Williams"));
  playerBase.add(new PlayerSearch(4066328, "Jarrett Allen", "Jarrett Allen"));
  playerBase.add(new PlayerSearch(4433620, "Emoni Bates", "Emoni Bates"));
  playerBase.add(new PlayerSearch(989, "Omar Cook", "Omar Cook"));
  playerBase.add(new PlayerSearch(4396907, "Darius Garland", "Darius Garland"));
  playerBase.add(new PlayerSearch(4065733, "Ty Jerome", "Ty Jerome"));
  playerBase.add(new PlayerSearch(2991043, "Caris LeVert", "Caris LeVert"));
  playerBase.add(new PlayerSearch(4066757, "Sam Merrill", "Sam Merrill"));
  playerBase.add(new PlayerSearch(3908809, "Donovan Mitchell", "Donovan Mitchell"));
  playerBase.add(new PlayerSearch(4432158, "Evan Mobley", "Evan Mobley"));
  playerBase.add(new PlayerSearch(2990969, "Georges Niang", "Georges Niang"));
  playerBase.add(new PlayerSearch(4432822, "Isaac Okoro", "Isaac Okoro"));
  playerBase.add(new PlayerSearch(4701233, "Craig Porter Jr.", "Craig Porter Jr."));
  playerBase.add(new PlayerSearch(4065778, "Max Strus", "Max Strus"));
  playerBase.add(new PlayerSearch(6474, "Tristan Thompson", "Tristan Thompson"));
  playerBase.add(new PlayerSearch(4702233, "JT Thor", "JT Thor"));
  playerBase.add(new PlayerSearch(4997539, "Luke Travers", "Luke Travers"));
  playerBase.add(new PlayerSearch(4683747, "Jaylon Tyson", "Jaylon Tyson"));
  playerBase.add(new PlayerSearch(3912848, "Dean Wade", "Dean Wade"));
  playerBase.add(new PlayerSearch(4396676, "Dexter Dennis", "Dexter Dennis"));
  playerBase.add(new PlayerSearch(2580782, "Spencer Dinwiddie", "Spencer Dinwiddie"));
  playerBase.add(new PlayerSearch(3945274, "Luka Doncic", "Luka Doncic"));
  playerBase.add(new PlayerSearch(4397693, "Kessler Edwards", "Kessler Edwards"));
  playerBase.add(new PlayerSearch(3102528, "Dante Exum", "Dante Exum"));
  playerBase.add(new PlayerSearch(4278049, "Daniel Gafford", "Daniel Gafford"));
  playerBase.add(new PlayerSearch(4708972, "Jazian Gortman", "Jazian Gortman"));
  playerBase.add(new PlayerSearch(4397014, "Quentin Grimes", "Quentin Grimes"));
  playerBase.add(new PlayerSearch(4868423, "Jaden Hardy", "Jaden Hardy"));
  playerBase.add(new PlayerSearch(6442, "Kyrie Irving", "Kyrie Irving"));
  playerBase.add(new PlayerSearch(2960236, "Maxi Kleber", "Maxi Kleber"));
  playerBase.add(new PlayerSearch(4067017, "A.J. Lawson", "A.J. Lawson"));
  playerBase.add(new PlayerSearch(4683688, "Dereck Lively II", "Dereck Lively II"));
  playerBase.add(new PlayerSearch(4278594, "Naji Marshall", "Naji Marshall"));
  playerBase.add(new PlayerSearch(4432872, "Emanuel Miller", "Emanuel Miller"));
  playerBase.add(new PlayerSearch(6461, "Markieff Morris", "Markieff Morris"));
  playerBase.add(new PlayerSearch(2531367, "Dwight Powell", "Dwight Powell"));
  playerBase.add(new PlayerSearch(4595400, "Olivier-Maxence Prosper", "Olivier-Maxence Prosper"));
  playerBase.add(new PlayerSearch(4897696, "Jamarion Sharp", "Jamarion Sharp"));
  playerBase.add(new PlayerSearch(6475, "Klay Thompson", "Klay Thompson"));
  playerBase.add(new PlayerSearch(4278078, "P.J. Washington", "P.J. Washington"));
  playerBase.add(new PlayerSearch(4397040, "Brandon Williams", "Brandon Williams"));
  playerBase.add(new PlayerSearch(4433268, "Trey Alexander", "Trey Alexander"));
  playerBase.add(new PlayerSearch(4431767, "Christian Braun", "Christian Braun"));
  playerBase.add(new PlayerSearch(4230557, "Vlatko Cancar", "Vlatko Cancar"));
  playerBase.add(new PlayerSearch(3064290, "Aaron Gordon", "Aaron Gordon"));
  playerBase.add(new PlayerSearch(4701225, "PJ Hall", "PJ Hall"));
  playerBase.add(new PlayerSearch(4433607, "DaRon Holmes II", "DaRon Holmes II"));
  playerBase.add(new PlayerSearch(3112335, "Nikola Jokic", "Nikola Jokic"));
  playerBase.add(new PlayerSearch(4592427, "Spencer Jones", "Spencer Jones"));
  playerBase.add(new PlayerSearch(3442, "DeAndre Jordan", "DeAndre Jordan"));
  playerBase.add(new PlayerSearch(4398356, "Gabe McGlothan", "Gabe McGlothan"));
  playerBase.add(new PlayerSearch(3936299, "Jamal Murray", "Jamal Murray"));
  playerBase.add(new PlayerSearch(4431690, "Zeke Nnaji", "Zeke Nnaji"));
  playerBase.add(new PlayerSearch(4398390, "Jalen Pickett", "Jalen Pickett"));
  playerBase.add(new PlayerSearch(4278104, "Michael Porter Jr.", "Michael Porter Jr."));
  playerBase.add(new PlayerSearch(3032978, "Dario Saric", "Dario Saric"));
  playerBase.add(new PlayerSearch(4432181, "Julian Strawther", "Julian Strawther"));
  playerBase.add(new PlayerSearch(4395620, "Hunter Tyson", "Hunter Tyson"));
  playerBase.add(new PlayerSearch(4576087, "Peyton Watson", "Peyton Watson"));
  playerBase.add(new PlayerSearch(3468, "Russell Westbrook", "Russell Westbrook"));
  playerBase.add(new PlayerSearch(4431776, "Jaylin Williams", "Jaylin Williams"));
  playerBase.add(new PlayerSearch(4433133, "Jahmir Young", "Jahmir Young"));
  playerBase.add(new PlayerSearch(3907822, "Malik Beasley", "Malik Beasley"));
  playerBase.add(new PlayerSearch(4432166, "Cade Cunningham", "Cade Cunningham"));
  playerBase.add(new PlayerSearch(4433621, "Jalen Duren", "Jalen Duren"));
  playerBase.add(new PlayerSearch(4597865, "Tosan Evbuomwan", "Tosan Evbuomwan"));
  playerBase.add(new PlayerSearch(3899664, "Simone Fontecchio", "Simone Fontecchio"));
  playerBase.add(new PlayerSearch(2528210, "Tim Hardaway Jr.", "Tim Hardaway Jr."));
  playerBase.add(new PlayerSearch(6440, "Tobias Harris", "Tobias Harris"));
  playerBase.add(new PlayerSearch(4683771, "Ron Holland II", "Ron Holland II"));
  playerBase.add(new PlayerSearch(4433218, "Jaden Ivey", "Jaden Ivey"));
  playerBase.add(new PlayerSearch(5107199, "Daniss Jenkins", "Daniss Jenkins"));
  playerBase.add(new PlayerSearch(5105340, "Bobi Klintman", "Bobi Klintman"));
  playerBase.add(new PlayerSearch(4592187, "Wendell Moore Jr.", "Wendell Moore Jr."));
  playerBase.add(new PlayerSearch(4278562, "Paul Reed", "Paul Reed"));
  playerBase.add(new PlayerSearch(4432107, "Marcus Sasser", "Marcus Sasser"));
  playerBase.add(new PlayerSearch(4432810, "Isaiah Stewart", "Isaiah Stewart"));
  playerBase.add(new PlayerSearch(4684742, "Ausar Thompson", "Ausar Thompson"));
  playerBase.add(new PlayerSearch(2993874, "Kyle Anderson", "Kyle Anderson"));
  playerBase.add(new PlayerSearch(4432187, "Reece Beekman", "Reece Beekman"));
  playerBase.add(new PlayerSearch(3975, "Stephen Curry", "Stephen Curry"));
  playerBase.add(new PlayerSearch(6589, "Draymond Green", "Draymond Green"));
  playerBase.add(new PlayerSearch(2990984, "Buddy Hield", "Buddy Hield"));
  playerBase.add(new PlayerSearch(4431684, "Trayce Jackson-Davis", "Trayce Jackson-Davis"));
  playerBase.add(new PlayerSearch(4433247, "Jonathan Kuminga", "Jonathan Kuminga"));
  playerBase.add(new PlayerSearch(3155535, "Kevon Looney", "Kevon Looney"));
  playerBase.add(new PlayerSearch(4066436, "De'Anthony Melton", "De'Anthony Melton"));
  playerBase.add(new PlayerSearch(4432171, "Moses Moody", "Moses Moody"));
  playerBase.add(new PlayerSearch(3134903, "Gary Payton II", "Gary Payton II"));
  playerBase.add(new PlayerSearch(4709138, "Brandin Podziemski", "Brandin Podziemski"));
  playerBase.add(new PlayerSearch(4593016, "Quinten Post", "Quinten Post"));
  playerBase.add(new PlayerSearch(4066889, "Jackson Rowe", "Jackson Rowe"));
  playerBase.add(new PlayerSearch(4997536, "Gui Santos", "Gui Santos"));
  playerBase.add(new PlayerSearch(4592714, "Pat Spencer", "Pat Spencer"));
  playerBase.add(new PlayerSearch(4066317, "Lindy Waters III", "Lindy Waters III"));
  playerBase.add(new PlayerSearch(3059319, "Andrew Wiggins", "Andrew Wiggins"));
  playerBase.add(new PlayerSearch(2991235, "Steven Adams", "Steven Adams"));
  playerBase.add(new PlayerSearch(3155526, "Dillon Brooks", "Dillon Brooks"));
  playerBase.add(new PlayerSearch(4592401, "N'Faly Dante", "N'Faly Dante"));
  playerBase.add(new PlayerSearch(4433192, "Tari Eason", "Tari Eason"));
  playerBase.add(new PlayerSearch(4437244, "Jalen Green", "Jalen Green"));
  playerBase.add(new PlayerSearch(3209, "Jeff Green", "Jeff Green"));
  playerBase.add(new PlayerSearch(4396629, "Nate Hinton", "Nate Hinton"));
  playerBase.add(new PlayerSearch(3922230, "Aaron Holiday", "Aaron Holiday"));
  playerBase.add(new PlayerSearch(3146557, "Jock Landale", "Jock Landale"));
  playerBase.add(new PlayerSearch(3911893, "Jack McVeigh", "Jack McVeigh"));
  playerBase.add(new PlayerSearch(4278588, "Jermaine Samuels Jr.", "Jermaine Samuels Jr."));
  playerBase.add(new PlayerSearch(4871144, "Alperen Sengun", "Alperen Sengun"));
  playerBase.add(new PlayerSearch(4711272, "Reed Sheppard", "Reed Sheppard"));
  playerBase.add(new PlayerSearch(4432639, "Jabari Smith Jr.", "Jabari Smith Jr."));
  playerBase.add(new PlayerSearch(3136777, "Jae'Sean Tate", "Jae'Sean Tate"));
  playerBase.add(new PlayerSearch(4684740, "Amen Thompson", "Amen Thompson"));
  playerBase.add(new PlayerSearch(2991230, "Fred VanVleet", "Fred VanVleet"));
  playerBase.add(new PlayerSearch(5105592, "Cam Whitmore", "Cam Whitmore"));
  playerBase.add(new PlayerSearch(4397821, "Nate Williams", "Nate Williams"));
  playerBase.add(new PlayerSearch(4433254, "Kendall Brown", "Kendall Brown"));
  playerBase.add(new PlayerSearch(4592699, "Enrique Freeman", "Enrique Freeman"));
  playerBase.add(new PlayerSearch(5157066, "Johnny Furphy", "Johnny Furphy"));
  playerBase.add(new PlayerSearch(4396993, "Tyrese Haliburton", "Tyrese Haliburton"));
  playerBase.add(new PlayerSearch(4432170, "Isaiah Jackson", "Isaiah Jackson"));
  playerBase.add(new PlayerSearch(4592829, "Quenton Jackson", "Quenton Jackson"));
  playerBase.add(new PlayerSearch(3999, "James Johnson", "James Johnson"));
  playerBase.add(new PlayerSearch(4683634, "Bennedict Mathurin", "Bennedict Mathurin"));
  playerBase.add(new PlayerSearch(2530530, "T.J. McConnell", "T.J. McConnell"));
  playerBase.add(new PlayerSearch(4395712, "Andrew Nembhard", "Andrew Nembhard"));
  playerBase.add(new PlayerSearch(4396909, "Aaron Nesmith", "Aaron Nesmith"));
  playerBase.add(new PlayerSearch(4592965, "Tristen Newton", "Tristen Newton"));
  playerBase.add(new PlayerSearch(4433076, "Ben Sheppard", "Ben Sheppard"));
  playerBase.add(new PlayerSearch(3149673, "Pascal Siakam", "Pascal Siakam"));
  playerBase.add(new PlayerSearch(4397134, "Cole Swider", "Cole Swider"));
  playerBase.add(new PlayerSearch(4278355, "Obi Toppin", "Obi Toppin"));
  playerBase.add(new PlayerSearch(3133628, "Myles Turner", "Myles Turner"));
  playerBase.add(new PlayerSearch(5106060, "Jarace Walker", "Jarace Walker"));
  playerBase.add(new PlayerSearch(4432808, "James Wiseman", "James Wiseman"));
  playerBase.add(new PlayerSearch(4277919, "Mo Bamba", "Mo Bamba"));
  playerBase.add(new PlayerSearch(3416, "Nicolas Batum", "Nicolas Batum"));
  playerBase.add(new PlayerSearch(4431752, "Kobe Brown", "Kobe Brown"));
  playerBase.add(new PlayerSearch(4845363, "Cam Christie", "Cam Christie"));
  playerBase.add(new PlayerSearch(4066387, "Amir Coffey", "Amir Coffey"));
  playerBase.add(new PlayerSearch(4431941, "RayJ Dennis", "RayJ Dennis"));
  playerBase.add(new PlayerSearch(2991139, "Kris Dunn", "Kris Dunn"));
  playerBase.add(new PlayerSearch(5165257, "Trentyn Flowers", "Trentyn Flowers"));
  playerBase.add(new PlayerSearch(3992, "James Harden", "James Harden"));
  playerBase.add(new PlayerSearch(4397449, "EJ Harkless", "EJ Harkless"));
  playerBase.add(new PlayerSearch(4592492, "Bones Hyland", "Bones Hyland"));
  playerBase.add(new PlayerSearch(4431699, "Kai Jones", "Kai Jones"));
  playerBase.add(new PlayerSearch(3936099, "Derrick Jones Jr.", "Derrick Jones Jr."));
  playerBase.add(new PlayerSearch(6450, "Kawhi Leonard", "Kawhi Leonard"));
  playerBase.add(new PlayerSearch(3907823, "Terance Mann", "Terance Mann"));
  playerBase.add(new PlayerSearch(4396818, "Jordan Miller", "Jordan Miller"));
  playerBase.add(new PlayerSearch(4397140, "Kevin Porter Jr.", "Kevin Porter Jr."));
  playerBase.add(new PlayerSearch(2595516, "Norman Powell", "Norman Powell"));
  playerBase.add(new PlayerSearch(3033, "P.J. Tucker", "P.J. Tucker"));
  playerBase.add(new PlayerSearch(4017837, "Ivica Zubac", "Ivica Zubac"));
  playerBase.add(new PlayerSearch(4397204, "Colin Castleton", "Colin Castleton"));
  playerBase.add(new PlayerSearch(4432582, "Max Christie", "Max Christie"));
  playerBase.add(new PlayerSearch(6583, "Anthony Davis", "Anthony Davis"));
  playerBase.add(new PlayerSearch(4278402, "Jordan Goodwin", "Jordan Goodwin"));
  playerBase.add(new PlayerSearch(4066648, "Rui Hachimura", "Rui Hachimura"));
  playerBase.add(new PlayerSearch(4397077, "Jaxson Hayes", "Jaxson Hayes"));
  playerBase.add(new PlayerSearch(4702702, "D'Moi Hodge", "D'Moi Hodge"));
  playerBase.add(new PlayerSearch(5105797, "Jalen Hood-Schifino", "Jalen Hood-Schifino"));
  playerBase.add(new PlayerSearch(4683774, "Bronny James", "Bronny James"));
  playerBase.add(new PlayerSearch(1966, "LeBron James", "LeBron James"));
  playerBase.add(new PlayerSearch(3950760, "Kylor Kelley", "Kylor Kelley"));
  playerBase.add(new PlayerSearch(4897943, "Dalton Knecht", "Dalton Knecht"));
  playerBase.add(new PlayerSearch(4431778, "Christian Koloko", "Christian Koloko"));
  playerBase.add(new PlayerSearch(4684286, "Maxwell Lewis", "Maxwell Lewis"));
  playerBase.add(new PlayerSearch(4432070, "Quincy Olivari", "Quincy Olivari"));
  playerBase.add(new PlayerSearch(4066457, "Austin Reaves", "Austin Reaves"));
  playerBase.add(new PlayerSearch(4395627, "Cam Reddish", "Cam Reddish"));
  playerBase.add(new PlayerSearch(3136776, "D'Angelo Russell", "D'Angelo Russell"));
  playerBase.add(new PlayerSearch(5104156, "Armel Traore", "Armel Traore"));
  playerBase.add(new PlayerSearch(4278077, "Jarred Vanderbilt", "Jarred Vanderbilt"));
  playerBase.add(new PlayerSearch(3137259, "Gabe Vincent", "Gabe Vincent"));
  playerBase.add(new PlayerSearch(3058254, "Christian Wood", "Christian Wood"));
  playerBase.add(new PlayerSearch(4066261, "Bam Adebayo", "Bam Adebayo"));
  playerBase.add(new PlayerSearch(3934723, "Thomas Bryant", "Thomas Bryant"));
  playerBase.add(new PlayerSearch(6429, "Alec Burks", "Alec Burks"));
  playerBase.add(new PlayerSearch(6430, "Jimmy Butler", "Jimmy Butler"));
  playerBase.add(new PlayerSearch(4432168, "Josh Christopher", "Josh Christopher"));
  playerBase.add(new PlayerSearch(4278373, "Caleb Daniels", "Caleb Daniels"));
  playerBase.add(new PlayerSearch(4395725, "Tyler Herro", "Tyler Herro"));
  playerBase.add(new PlayerSearch(4291678, "Haywood Highsmith", "Haywood Highsmith"));
  playerBase.add(new PlayerSearch(4432848, "Jaime Jaquez Jr.", "Jaime Jaquez Jr."));
  playerBase.add(new PlayerSearch(4431786, "Keshad Johnson", "Keshad Johnson"));
  playerBase.add(new PlayerSearch(4997528, "Nikola Jovic", "Nikola Jovic"));
  playerBase.add(new PlayerSearch(4601025, "Pelle Larsson", "Pelle Larsson"));
  playerBase.add(new PlayerSearch(4395652, "Nassir Little", "Nassir Little"));
  playerBase.add(new PlayerSearch(3449, "Kevin Love", "Kevin Love"));
  playerBase.add(new PlayerSearch(4592979, "Zyon Pullin", "Zyon Pullin"));
  playerBase.add(new PlayerSearch(2581190, "Josh Richardson", "Josh Richardson"));
  playerBase.add(new PlayerSearch(3157465, "Duncan Robinson", "Duncan Robinson"));
  playerBase.add(new PlayerSearch(3074752, "Terry Rozier", "Terry Rozier"));
  playerBase.add(new PlayerSearch(4066993, "Dru Smith", "Dru Smith"));
  playerBase.add(new PlayerSearch(4432117, "Isaiah Stevens", "Isaiah Stevens"));
  playerBase.add(new PlayerSearch(5105623, "Kel'el Ware", "Kel'el Ware"));
  playerBase.add(new PlayerSearch(4397072, "James Akinjo", "James Akinjo"));
  playerBase.add(new PlayerSearch(3032977, "Giannis Antetokounmpo", "Giannis Antetokounmpo"));
  playerBase.add(new PlayerSearch(4432179, "MarJon Beauchamp", "MarJon Beauchamp"));
  playerBase.add(new PlayerSearch(2578239, "Pat Connaughton", "Pat Connaughton"));
  playerBase.add(new PlayerSearch(4397475, "AJ Green", "AJ Green"));
  playerBase.add(new PlayerSearch(4432190, "Andre Jackson Jr.", "Andre Jackson Jr."));
  playerBase.add(new PlayerSearch(5170947, "AJ Johnson", "AJ Johnson"));
  playerBase.add(new PlayerSearch(6606, "Damian Lillard", "Damian Lillard"));
  playerBase.add(new PlayerSearch(4433622, "Chris Livingston", "Chris Livingston"));
  playerBase.add(new PlayerSearch(3448, "Brook Lopez", "Brook Lopez"));
  playerBase.add(new PlayerSearch(6609, "Khris Middleton", "Khris Middleton"));
  playerBase.add(new PlayerSearch(3893059, "Anzejs Pasecniks", "Anzejs Pasecniks"));
  playerBase.add(new PlayerSearch(3064482, "Bobby Portis", "Bobby Portis"));
  playerBase.add(new PlayerSearch(2990962, "Taurean Prince", "Taurean Prince"));
  playerBase.add(new PlayerSearch(4397347, "Liam Robbins", "Liam Robbins"));
  playerBase.add(new PlayerSearch(4591725, "Ryan Rollins", "Ryan Rollins"));
  playerBase.add(new PlayerSearch(5167876, "Tyler Smith", "Tyler Smith"));
  playerBase.add(new PlayerSearch(4277843, "Gary Trent Jr.", "Gary Trent Jr."));
  playerBase.add(new PlayerSearch(4279532, "Stanley Umude", "Stanley Umude"));
  playerBase.add(new PlayerSearch(3064447, "Delon Wright", "Delon Wright"));
  playerBase.add(new PlayerSearch(4278039, "Nickeil Alexander-Walker", "Nickeil Alexander-Walker"));
  playerBase.add(new PlayerSearch(4432247, "Jaylen Clark", "Jaylen Clark"));
  playerBase.add(new PlayerSearch(3195, "Mike Conley", "Mike Conley"));
  playerBase.add(new PlayerSearch(4684275, "Rob Dillingham", "Rob Dillingham"));
  playerBase.add(new PlayerSearch(3923250, "PJ Dozier", "PJ Dozier"));
  playerBase.add(new PlayerSearch(4594268, "Anthony Edwards", "Anthony Edwards"));
  playerBase.add(new PlayerSearch(4431816, "Jesse Edwards", "Jesse Edwards"));
  playerBase.add(new PlayerSearch(4277951, "Luka Garza", "Luka Garza"));
  playerBase.add(new PlayerSearch(3032976, "Rudy Gobert", "Rudy Gobert"));
  playerBase.add(new PlayerSearch(2968436, "Joe Ingles", "Joe Ingles"));
  playerBase.add(new PlayerSearch(4431671, "Jaden McDaniels", "Jaden McDaniels"));
  playerBase.add(new PlayerSearch(5044385, "Leonard Miller", "Leonard Miller"));
  playerBase.add(new PlayerSearch(4687718, "Josh Minott", "Josh Minott"));
  playerBase.add(new PlayerSearch(4432176, "Daishen Nix", "Daishen Nix"));
  playerBase.add(new PlayerSearch(4396971, "Naz Reid", "Naz Reid"));
  playerBase.add(new PlayerSearch(4432847, "Terrence Shannon Jr.", "Terrence Shannon Jr."));
  playerBase.add(new PlayerSearch(3136195, "Karl-Anthony Towns", "Karl-Anthony Towns"));
  playerBase.add(new PlayerSearch(3593, "Bojan Bogdanovic", "Bojan Bogdanovic"));
  playerBase.add(new PlayerSearch(4066450, "Armoni Brooks", "Armoni Brooks"));
  playerBase.add(new PlayerSearch(4278067, "Nic Claxton", "Nic Claxton"));
  playerBase.add(new PlayerSearch(4712896, "Noah Clowney", "Noah Clowney"));
  playerBase.add(new PlayerSearch(5159486, "Yongxi Cui", "Yongxi Cui"));
  playerBase.add(new PlayerSearch(2578185, "Dorian Finney-Smith", "Dorian Finney-Smith"));
  playerBase.add(new PlayerSearch(4683024, "Killian Hayes", "Killian Hayes"));
  playerBase.add(new PlayerSearch(3138196, "Cameron Johnson", "Cameron Johnson"));
  playerBase.add(new PlayerSearch(4432192, "Keon Johnson", "Keon Johnson"));
  playerBase.add(new PlayerSearch(5149711, "Jaylen Martin", "Jaylen Martin"));
  playerBase.add(new PlayerSearch(4397179, "Tyrese Martin", "Tyrese Martin"));
  playerBase.add(new PlayerSearch(3915195, "Shake Milton", "Shake Milton"));
  playerBase.add(new PlayerSearch(3032979, "Dennis Schroder", "Dennis Schroder"));
  playerBase.add(new PlayerSearch(4432194, "Day'Ron Sharpe", "Day'Ron Sharpe"));
  playerBase.add(new PlayerSearch(3907387, "Ben Simmons", "Ben Simmons"));
  playerBase.add(new PlayerSearch(4432174, "Cam Thomas", "Cam Thomas"));
  playerBase.add(new PlayerSearch(4431675, "Trendon Watford", "Trendon Watford"));
  playerBase.add(new PlayerSearch(4432735, "Dariq Whitehead", "Dariq Whitehead"));
  playerBase.add(new PlayerSearch(4433137, "Ziaire Williams", "Ziaire Williams"));
  playerBase.add(new PlayerSearch(4431714, "Jalen Wilson", "Jalen Wilson"));
  playerBase.add(new PlayerSearch(4431679, "Precious Achiuwa", "Precious Achiuwa"));
  playerBase.add(new PlayerSearch(3934719, "OG Anunoby", "OG Anunoby"));
  playerBase.add(new PlayerSearch(3136779, "Keita Bates-Diop", "Keita Bates-Diop"));
  playerBase.add(new PlayerSearch(3147657, "Mikal Bridges", "Mikal Bridges"));
  playerBase.add(new PlayerSearch(3934672, "Jalen Brunson", "Jalen Brunson"));
  playerBase.add(new PlayerSearch(5211983, "Pacome Dadiet", "Pacome Dadiet"));
  playerBase.add(new PlayerSearch(3934673, "Donte DiVincenzo", "Donte DiVincenzo"));
  playerBase.add(new PlayerSearch(3062679, "Josh Hart", "Josh Hart"));
  playerBase.add(new PlayerSearch(4871141, "Ariel Hukporti", "Ariel Hukporti"));
  playerBase.add(new PlayerSearch(4433225, "Tyler Kolek", "Tyler Kolek"));
  playerBase.add(new PlayerSearch(4431823, "Miles McBride", "Miles McBride"));
  playerBase.add(new PlayerSearch(4411057, "Kevin McCullar Jr.", "Kevin McCullar Jr."));
  playerBase.add(new PlayerSearch(4278052, "Chuma Okeke", "Chuma Okeke"));
  playerBase.add(new PlayerSearch(3064230, "Cameron Payne", "Cameron Payne"));
  playerBase.add(new PlayerSearch(3064514, "Julius Randle", "Julius Randle"));
  playerBase.add(new PlayerSearch(4351852, "Mitchell Robinson", "Mitchell Robinson"));
  playerBase.add(new PlayerSearch(3914044, "Landry Shamet", "Landry Shamet"));
  playerBase.add(new PlayerSearch(4277922, "Jericho Sims", "Jericho Sims"));
  playerBase.add(new PlayerSearch(4592461, "Jacob Toppin", "Jacob Toppin"));
  playerBase.add(new PlayerSearch(4432809, "Cole Anthony", "Cole Anthony"));
  playerBase.add(new PlayerSearch(4432573, "Paolo Banchero", "Paolo Banchero"));
  playerBase.add(new PlayerSearch(4348700, "Goga Bitadze", "Goga Bitadze"));
  playerBase.add(new PlayerSearch(4712849, "Anthony Black", "Anthony Black"));
  playerBase.add(new PlayerSearch(2581018, "Kentavious Caldwell-Pope", "Kentavious Caldwell-Pope"));
  playerBase.add(new PlayerSearch(4277847, "Wendell Carter Jr.", "Wendell Carter Jr."));
  playerBase.add(new PlayerSearch(4277928, "Jarrett Culver", "Jarrett Culver"));
  playerBase.add(new PlayerSearch(4702382, "Tristan da Silva", "Tristan da Silva"));
  playerBase.add(new PlayerSearch(2999547, "Gary Harris", "Gary Harris"));
  playerBase.add(new PlayerSearch(4433623, "Caleb Houstan", "Caleb Houstan"));
  playerBase.add(new PlayerSearch(5105806, "Jett Howard", "Jett Howard"));
  playerBase.add(new PlayerSearch(4065654, "Jonathan Isaac", "Jonathan Isaac"));
  playerBase.add(new PlayerSearch(6446, "Cory Joseph", "Cory Joseph"));
  playerBase.add(new PlayerSearch(4397071, "Mac McClung", "Mac McClung"));
  playerBase.add(new PlayerSearch(4409222, "Trevelin Queen", "Trevelin Queen"));
  playerBase.add(new PlayerSearch(4398207, "Jalen Slawson", "Jalen Slawson"));
  playerBase.add(new PlayerSearch(4396972, "Javonte Smart", "Javonte Smart"));
  playerBase.add(new PlayerSearch(4432165, "Jalen Suggs", "Jalen Suggs"));
  playerBase.add(new PlayerSearch(4278516, "Ethan Thompson", "Ethan Thompson"));
  playerBase.add(new PlayerSearch(4566434, "Franz Wagner", "Franz Wagner"));
  playerBase.add(new PlayerSearch(3150844, "Moritz Wagner", "Moritz Wagner"));
  playerBase.add(new PlayerSearch(5105637, "Adem Bona", "Adem Bona"));
  playerBase.add(new PlayerSearch(4701234, "Ricky Council IV", "Ricky Council IV"));
  playerBase.add(new PlayerSearch(4066786, "Jeff Dowtin Jr.", "Jeff Dowtin Jr."));
  playerBase.add(new PlayerSearch(6585, "Andre Drummond", "Andre Drummond"));
  playerBase.add(new PlayerSearch(3059318, "Joel Embiid", "Joel Embiid"));
  playerBase.add(new PlayerSearch(4640265, "Max Fielder", "Max Fielder"));
  playerBase.add(new PlayerSearch(4251, "Paul George", "Paul George"));
  playerBase.add(new PlayerSearch(3431, "Eric Gordon", "Eric Gordon"));
  playerBase.add(new PlayerSearch(6443, "Reggie Jackson", "Reggie Jackson"));
  playerBase.add(new PlayerSearch(4713010, "David Jones", "David Jones"));
  playerBase.add(new PlayerSearch(3012, "Kyle Lowry", "Kyle Lowry"));
  playerBase.add(new PlayerSearch(3138160, "Caleb Martin", "Caleb Martin"));
  playerBase.add(new PlayerSearch(4431828, "KJ Martin", "KJ Martin"));
  playerBase.add(new PlayerSearch(4431678, "Tyrese Maxey", "Tyrese Maxey"));
  playerBase.add(new PlayerSearch(4683778, "Jared McCain", "Jared McCain"));
  playerBase.add(new PlayerSearch(4684729, "Judah Mintz", "Judah Mintz"));
  playerBase.add(new PlayerSearch(3133603, "Kelly Oubre Jr.", "Kelly Oubre Jr."));
  playerBase.add(new PlayerSearch(4431720, "Lester Quinones", "Lester Quinones"));
  playerBase.add(new PlayerSearch(4017844, "Guerschon Yabusele", "Guerschon Yabusele"));
  playerBase.add(new PlayerSearch(3135045, "Grayson Allen", "Grayson Allen"));
  playerBase.add(new PlayerSearch(6580, "Bradley Beal", "Bradley Beal"));
  playerBase.add(new PlayerSearch(4397102, "Bol Bol", "Bol Bol"));
  playerBase.add(new PlayerSearch(3136193, "Devin Booker", "Devin Booker"));
  playerBase.add(new PlayerSearch(4432946, "Jalen Bridges", "Jalen Bridges"));
  playerBase.add(new PlayerSearch(4888725, "Ryan Dunn", "Ryan Dunn"));
  playerBase.add(new PlayerSearch(3202, "Kevin Durant", "Kevin Durant"));
  playerBase.add(new PlayerSearch(4278585, "Collin Gillespie", "Collin Gillespie"));
  playerBase.add(new PlayerSearch(4601023, "Oso Ighodaro", "Oso Ighodaro"));
  playerBase.add(new PlayerSearch(3135046, "Tyus Jones", "Tyus Jones"));
  playerBase.add(new PlayerSearch(2595209, "Damion Lee", "Damion Lee"));
  playerBase.add(new PlayerSearch(3059310, "Monte Morris", "Monte Morris"));
  playerBase.add(new PlayerSearch(3102530, "Jusuf Nurkic", "Jusuf Nurkic"));
  playerBase.add(new PlayerSearch(2583632, "Royce O'Neale", "Royce O'Neale"));
  playerBase.add(new PlayerSearch(4065663, "Josh Okogie", "Josh Okogie"));
  playerBase.add(new PlayerSearch(2488653, "Mason Plumlee", "Mason Plumlee"));
  playerBase.add(new PlayerSearch(4683749, "TyTy Washington Jr.", "TyTy Washington Jr."));
  playerBase.add(new PlayerSearch(4683021, "Deni Avdija", "Deni Avdija"));
  playerBase.add(new PlayerSearch(4278129, "Deandre Ayton", "Deandre Ayton"));
  playerBase.add(new PlayerSearch(4397885, "Dalano Banton", "Dalano Banton"));
  playerBase.add(new PlayerSearch(4431736, "Toumani Camara", "Toumani Camara"));
  playerBase.add(new PlayerSearch(5105565, "Donovan Clingan", "Donovan Clingan"));
  playerBase.add(new PlayerSearch(4423884, "Henri Drell", "Henri Drell"));
  playerBase.add(new PlayerSearch(3133601, "Devonte' Graham", "Devonte' Graham"));
  playerBase.add(new PlayerSearch(2991070, "Jerami Grant", "Jerami Grant"));
  playerBase.add(new PlayerSearch(4683678, "Scoot Henderson", "Scoot Henderson"));
  playerBase.add(new PlayerSearch(4576086, "Bryce McGowens", "Bryce McGowens"));
  playerBase.add(new PlayerSearch(4278111, "Justin Minaya", "Justin Minaya"));
  playerBase.add(new PlayerSearch(4066808, "Taze Moore", "Taze Moore"));
  playerBase.add(new PlayerSearch(4594326, "Kris Murray", "Kris Murray"));
  playerBase.add(new PlayerSearch(4066268, "Duop Reath", "Duop Reath"));
  playerBase.add(new PlayerSearch(5099752, "Rayan Rupert", "Rayan Rupert"));
  playerBase.add(new PlayerSearch(4914336, "Shaedon Sharpe", "Shaedon Sharpe"));
  playerBase.add(new PlayerSearch(4351851, "Anfernee Simons", "Anfernee Simons"));
  playerBase.add(new PlayerSearch(3907498, "Matisse Thybulle", "Matisse Thybulle"));
  playerBase.add(new PlayerSearch(4432446, "Jabari Walker", "Jabari Walker"));
  playerBase.add(new PlayerSearch(4066211, "Robert Williams III", "Robert Williams III"));
  playerBase.add(new PlayerSearch(4433188, "Devin Carter", "Devin Carter"));
  playerBase.add(new PlayerSearch(4592857, "Isaiah Crawford", "Isaiah Crawford"));
  playerBase.add(new PlayerSearch(3978, "DeMar DeRozan", "DeMar DeRozan"));
  playerBase.add(new PlayerSearch(4593106, "Boogie Ellis", "Boogie Ellis"));
  playerBase.add(new PlayerSearch(4702177, "Keon Ellis", "Keon Ellis"));
  playerBase.add(new PlayerSearch(4066259, "De'Aaron Fox", "De'Aaron Fox"));
  playerBase.add(new PlayerSearch(4066372, "Kevin Huerter", "Kevin Huerter"));
  playerBase.add(new PlayerSearch(4433378, "Colby Jones", "Colby Jones"));
  playerBase.add(new PlayerSearch(5107818, "Isaac Jones", "Isaac Jones"));
  playerBase.add(new PlayerSearch(4395704, "Mason Jones", "Mason Jones"));
  playerBase.add(new PlayerSearch(2596107, "Alex Len", "Alex Len"));
  playerBase.add(new PlayerSearch(3136196, "Trey Lyles", "Trey Lyles"));
  playerBase.add(new PlayerSearch(4066731, "Jalen McDaniels", "Jalen McDaniels"));
  playerBase.add(new PlayerSearch(3134916, "Jordan McLaughlin", "Jordan McLaughlin"));
  playerBase.add(new PlayerSearch(4066262, "Malik Monk", "Malik Monk"));
  playerBase.add(new PlayerSearch(4594327, "Keegan Murray", "Keegan Murray"));
  playerBase.add(new PlayerSearch(4593049, "Orlando Robinson", "Orlando Robinson"));
  playerBase.add(new PlayerSearch(3155942, "Domantas Sabonis", "Domantas Sabonis"));
  playerBase.add(new PlayerSearch(4279815, "Terry Taylor", "Terry Taylor"));
  playerBase.add(new PlayerSearch(6578, "Harrison Barnes", "Harrison Barnes"));
  playerBase.add(new PlayerSearch(4397886, "Charles Bassey", "Charles Bassey"));
  playerBase.add(new PlayerSearch(4432162, "Brandon Boston Jr.", "Brandon Boston Jr."));
  playerBase.add(new PlayerSearch(4565201, "Malaki Branham", "Malaki Branham"));
  playerBase.add(new PlayerSearch(4845367, "Stephon Castle", "Stephon Castle"));
  playerBase.add(new PlayerSearch(4592479, "Julian Champagnie", "Julian Champagnie"));
  playerBase.add(new PlayerSearch(5081727, "Sidy Cissoko", "Sidy Cissoko"));
  playerBase.add(new PlayerSearch(4066650, "Zach Collins", "Zach Collins"));
  playerBase.add(new PlayerSearch(4397107, "David Duke Jr.", "David Duke Jr."));
  playerBase.add(new PlayerSearch(4066668, "Malachi Flynn", "Malachi Flynn"));
  playerBase.add(new PlayerSearch(4433618, "Harrison Ingram", "Harrison Ingram"));
  playerBase.add(new PlayerSearch(4395723, "Keldon Johnson", "Keldon Johnson"));
  playerBase.add(new PlayerSearch(4395626, "Tre Jones", "Tre Jones"));
  playerBase.add(new PlayerSearch(4278580, "Sandro Mamukelashvili", "Sandro Mamukelashvili"));
  playerBase.add(new PlayerSearch(5177362, "Riley Minix", "Riley Minix"));
  playerBase.add(new PlayerSearch(2779, "Chris Paul", "Chris Paul"));
  playerBase.add(new PlayerSearch(4610139, "Jeremy Sochan", "Jeremy Sochan"));
  playerBase.add(new PlayerSearch(4395630, "Devin Vassell", "Devin Vassell"));
  playerBase.add(new PlayerSearch(5104157, "Victor Wembanyama", "Victor Wembanyama"));
  playerBase.add(new PlayerSearch(4683935, "Blake Wesley", "Blake Wesley"));
  playerBase.add(new PlayerSearch(2991350, "Alex Caruso", "Alex Caruso"));
  playerBase.add(new PlayerSearch(4997526, "Ousmane Dieng", "Ousmane Dieng"));
  playerBase.add(new PlayerSearch(4397020, "Luguentz Dort", "Luguentz Dort"));
  playerBase.add(new PlayerSearch(4432971, "Alex Ducas", "Alex Ducas"));
  playerBase.add(new PlayerSearch(4397654, "Adam Flagler", "Adam Flagler"));
  playerBase.add(new PlayerSearch(4278073, "Shai Gilgeous-Alexander", "Shai Gilgeous-Alexander"));
  playerBase.add(new PlayerSearch(4222252, "Isaiah Hartenstein", "Isaiah Hartenstein"));
  playerBase.add(new PlayerSearch(4433255, "Chet Holmgren", "Chet Holmgren"));
  playerBase.add(new PlayerSearch(4395702, "Isaiah Joe", "Isaiah Joe"));
  playerBase.add(new PlayerSearch(4702159, "Dillon Jones", "Dillon Jones"));
  playerBase.add(new PlayerSearch(4900671, "Ajay Mitchell", "Ajay Mitchell"));
  playerBase.add(new PlayerSearch(5159925, "Nikola Topic", "Nikola Topic"));
  playerBase.add(new PlayerSearch(4683692, "Cason Wallace", "Cason Wallace"));
  playerBase.add(new PlayerSearch(4397183, "Aaron Wiggins", "Aaron Wiggins"));
  playerBase.add(new PlayerSearch(4593803, "Jalen Williams", "Jalen Williams"));
  playerBase.add(new PlayerSearch(4432823, "Jaylin Williams", "Jaylin Williams"));
  playerBase.add(new PlayerSearch(3133626, "Kenrich Williams", "Kenrich Williams"));
  playerBase.add(new PlayerSearch(2528426, "Jordan Clarkson", "Jordan Clarkson"));
  playerBase.add(new PlayerSearch(4683766, "Isaiah Collier", "Isaiah Collier"));
  playerBase.add(new PlayerSearch(3908845, "John Collins", "John Collins"));
  playerBase.add(new PlayerSearch(3914285, "Drew Eubanks", "Drew Eubanks"));
  playerBase.add(new PlayerSearch(4684793, "Kyle Filipowski", "Kyle Filipowski"));
  playerBase.add(new PlayerSearch(4433627, "Keyonte George", "Keyonte George"));
  playerBase.add(new PlayerSearch(4684806, "Taylor Hendricks", "Taylor Hendricks"));
  playerBase.add(new PlayerSearch(4432817, "Johnny Juzang", "Johnny Juzang"));
  playerBase.add(new PlayerSearch(4433136, "Walker Kessler", "Walker Kessler"));
  playerBase.add(new PlayerSearch(4066336, "Lauri Markkanen", "Lauri Markkanen"));
  playerBase.add(new PlayerSearch(4004, "Patty Mills", "Patty Mills"));
  playerBase.add(new PlayerSearch(3133602, "Svi Mykhailiuk", "Svi Mykhailiuk"));
  playerBase.add(new PlayerSearch(4066399, "Micah Potter", "Micah Potter"));
  playerBase.add(new PlayerSearch(4397916, "Jason Preston", "Jason Preston"));
  playerBase.add(new PlayerSearch(5110117, "Babacar Sane", "Babacar Sane"));
  playerBase.add(new PlayerSearch(5105839, "Brice Sensabaugh", "Brice Sensabaugh"));
  playerBase.add(new PlayerSearch(4277811, "Collin Sexton", "Collin Sexton"));
  playerBase.add(new PlayerSearch(4432827, "Oscar Tshiebwe", "Oscar Tshiebwe"));
  playerBase.add(new PlayerSearch(4895758, "Cody Williams", "Cody Williams"));
  playerBase.add(new PlayerSearch(4277848, "Marvin Bagley III", "Marvin Bagley III"));
  playerBase.add(new PlayerSearch(4433246, "Patrick Baldwin Jr.", "Patrick Baldwin Jr."));
  playerBase.add(new PlayerSearch(4397136, "Saddiq Bey", "Saddiq Bey"));
  playerBase.add(new PlayerSearch(2566769, "Malcolm Brogdon", "Malcolm Brogdon"));
  playerBase.add(new PlayerSearch(4395695, "Jared Butler", "Jared Butler"));
  playerBase.add(new PlayerSearch(4845374, "Bub Carrington", "Bub Carrington"));
  playerBase.add(new PlayerSearch(4432907, "Justin Champagnie", "Justin Champagnie"));
  playerBase.add(new PlayerSearch(5104155, "Bilal Coulibaly", "Bilal Coulibaly"));
  playerBase.add(new PlayerSearch(4432356, "Johnny Davis", "Johnny Davis"));
  playerBase.add(new PlayerSearch(5174563, "Kyshawn George", "Kyshawn George"));
  playerBase.add(new PlayerSearch(2581184, "Anthony Gill", "Anthony Gill"));
  playerBase.add(new PlayerSearch(2993370, "Richaun Holmes", "Richaun Holmes"));
  playerBase.add(new PlayerSearch(3947736, "Caleb Homesley", "Caleb Homesley"));
  playerBase.add(new PlayerSearch(4280151, "Corey Kispert", "Corey Kispert"));
  playerBase.add(new PlayerSearch(3134907, "Kyle Kuzma", "Kyle Kuzma"));
  playerBase.add(new PlayerSearch(4277956, "Jordan Poole", "Jordan Poole"));
  playerBase.add(new PlayerSearch(5160992, "Alex Sarr", "Alex Sarr"));
  playerBase.add(new PlayerSearch(6477, "Jonas Valanciunas", "Jonas Valanciunas"));
  playerBase.add(new PlayerSearch(4997537, "Tristan Vukcevic", "Tristan Vukcevic"));
  playerBase.add(new PlayerSearch(4397018, "Ochai Agbaji", "Ochai Agbaji"));
  playerBase.add(new PlayerSearch(4433134, "Scottie Barnes", "Scottie Barnes"));
  playerBase.add(new PlayerSearch(4395625, "RJ Barrett", "RJ Barrett"));
  playerBase.add(new PlayerSearch(4431893, "Jamison Battle", "Jamison Battle"));
  playerBase.add(new PlayerSearch(3948153, "Chris Boucher", "Chris Boucher"));
  playerBase.add(new PlayerSearch(4065670, "Bruce Brown", "Bruce Brown"));
  playerBase.add(new PlayerSearch(4592435, "Branden Carlson", "Branden Carlson"));
  playerBase.add(new PlayerSearch(4432820, "D.J. Carton", "D.J. Carton"));
  playerBase.add(new PlayerSearch(5211984, "Ulrich Chomche", "Ulrich Chomche"));
  playerBase.add(new PlayerSearch(5106258, "Gradey Dick", "Gradey Dick"));
  playerBase.add(new PlayerSearch(4277952, "Bruno Fernando", "Bruno Fernando"));
  playerBase.add(new PlayerSearch(4278053, "Davion Mitchell", "Davion Mitchell"));
  playerBase.add(new PlayerSearch(5107897, "Jonathan Mogbo", "Jonathan Mogbo"));
  playerBase.add(new PlayerSearch(2489663, "Kelly Olynyk", "Kelly Olynyk"));
  playerBase.add(new PlayerSearch(3134908, "Jakob Poeltl", "Jakob Poeltl"));
  playerBase.add(new PlayerSearch(4395724, "Immanuel Quickley", "Immanuel Quickley"));
  playerBase.add(new PlayerSearch(4397119, "Jared Rhoden", "Jared Rhoden"));
  playerBase.add(new PlayerSearch(4432241, "Jamal Shead", "Jamal Shead"));
  playerBase.add(new PlayerSearch(4023, "Garrett Temple", "Garrett Temple"));
  playerBase.add(new PlayerSearch(4684272, "Ja'Kobe Walter", "Ja'Kobe Walter"));
  playerBase.add(new PlayerSearch(4593125, "Santi Aldama", "Santi Aldama"));
  playerBase.add(new PlayerSearch(4431674, "Armando Bacot", "Armando Bacot"));
  playerBase.add(new PlayerSearch(4066320, "Desmond Bane", "Desmond Bane"));
  playerBase.add(new PlayerSearch(3906665, "Brandon Clarke", "Brandon Clarke"));
  playerBase.add(new PlayerSearch(4600663, "Zach Edey", "Zach Edey"));
  playerBase.add(new PlayerSearch(4065731, "Jay Huff", "Jay Huff"));
  playerBase.add(new PlayerSearch(5105550, "GG Jackson II", "GG Jackson II"));
  playerBase.add(new PlayerSearch(4277961, "Jaren Jackson Jr.", "Jaren Jackson Jr."));
  playerBase.add(new PlayerSearch(5159895, "Yuki Kawamura", "Yuki Kawamura"));
  playerBase.add(new PlayerSearch(3913174, "Luke Kennard", "Luke Kennard"));
  playerBase.add(new PlayerSearch(3134932, "John Konchar", "John Konchar"));
  playerBase.add(new PlayerSearch(4592691, "Jake LaRavia", "Jake LaRavia"));
  playerBase.add(new PlayerSearch(4279888, "Ja Morant", "Ja Morant"));
  playerBase.add(new PlayerSearch(4066851, "Miye Oni", "Miye Oni"));
  playerBase.add(new PlayerSearch(5184018, "Maozinha Pereira", "Maozinha Pereira"));
  playerBase.add(new PlayerSearch(2990992, "Marcus Smart", "Marcus Smart"));
  playerBase.add(new PlayerSearch(4433083, "Cam Spencer", "Cam Spencer"));
  playerBase.add(new PlayerSearch(5112087, "Jaylen Wells", "Jaylen Wells"));
  playerBase.add(new PlayerSearch(4397227, "Vince Williams Jr.", "Vince Williams Jr."));
  playerBase.add(new PlayerSearch(4432816, "LaMelo Ball", "LaMelo Ball"));
  playerBase.add(new PlayerSearch(4066383, "Miles Bridges", "Miles Bridges"));
  playerBase.add(new PlayerSearch(2326307, "Seth Curry", "Seth Curry"));
  playerBase.add(new PlayerSearch(4433249, "Moussa Diabate", "Moussa Diabate"));
  playerBase.add(new PlayerSearch(4277892, "Marcus Garrett", "Marcus Garrett"));
  playerBase.add(new PlayerSearch(3986, "Taj Gibson", "Taj Gibson"));
  playerBase.add(new PlayerSearch(4432811, "Josh Green", "Josh Green"));
  playerBase.add(new PlayerSearch(4395714, "Keyontae Johnson", "Keyontae Johnson"));
  playerBase.add(new PlayerSearch(4432819, "Tre Mann", "Tre Mann"));
  playerBase.add(new PlayerSearch(3138161, "Cody Martin", "Cody Martin"));
  playerBase.add(new PlayerSearch(4397249, "Caleb McConnell", "Caleb McConnell"));
  playerBase.add(new PlayerSearch(3102532, "Vasilije Micic", "Vasilije Micic"));
  playerBase.add(new PlayerSearch(4433287, "Brandon Miller", "Brandon Miller"));
  playerBase.add(new PlayerSearch(4278076, "Nick Richards", "Nick Richards"));
  playerBase.add(new PlayerSearch(5211176, "Tidjane Salaun", "Tidjane Salaun"));
  playerBase.add(new PlayerSearch(4683834, "K.J. Simpson", "K.J. Simpson"));
  playerBase.add(new PlayerSearch(4683686, "Nick Smith Jr.", "Nick Smith Jr."));
  playerBase.add(new PlayerSearch(4066218, "Grant Williams", "Grant Williams"));
  playerBase.add(new PlayerSearch(4701232, "Mark Williams", "Mark Williams"));
  }
}
